GET https://localhost:3001/api/userService/getAccounts

###
GET http://localhost:3000/api/userService/getAccount/616533ddd7f00efca6a02f11

###

POST http://localhost:3000/api/userService/createAccount
Content-Type: application/json

{
    "username": "user6",
    "fullname": "user 6",
    "password": "12344",
    "email": "user6@python.com"
}

###
DELETE http://localhost:3000/api/userService/deleteAccount
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhc2hpc2hAYXNkLmNvbSIsImlhdCI6MTYzNDYyNjQ4MiwiZXhwIjoxNjM0NjMzNjgyfQ.RyHLTQl2Wh_0nhbY7wZLUEfqxSikcPs5ftEAyLW9MK4"
}

###
PATCH http://localhost:3000/api/userService/modifyAccount
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhc2hpc2hAYXNkLmNvbSIsImlhdCI6MTYzNDYyNjc2NCwiZXhwIjoxNjM0NjMzOTY0fQ.Yw5NUNzZHTmjl0DoDwz7Ll27CsxPfSsd2z-RisD2iww",
    "password": "1234"
}

###
//Login
POST http://localhost:3000/api/userService/login
Content-Type: application/json

{
    "email": "user6@python.com",
    "password": "12344"
}

###
//Logout
POST http://localhost:3000/api/userService/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNjM0OTg3Mjc5LCJleHAiOjE2MzQ5OTQ0Nzl9.hFU4g5EdeqT0CuSM91zNJuQ7SovYruh1qHMCb8NDvGQ"
}

###

//view messages in dm (initial GET request)
POST http://localhost:3000/api/dms/61757464b02926a3f080ee61/view
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsYW4iLCJpYXQiOjE2MzUxMDAzNDEsImV4cCI6MTYzNTEwNzU0MX0.MhBIJkzUanoU1NFIxcWpky_N1HR6TvDeBu4A-voUtA0"
}

###

//create dm after querying username
POST http://localhost:3000/api/dms/create
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsYW4iLCJpYXQiOjE2MzUwNjg3NTcsImV4cCI6MTYzNTA3NTk1N30.rlGQ7KFTe9XUW6DkcjpWtIrGLKeQ0dA4TCBY452ZKzE",
    "username" : "akkka"
}

###

POST http://localhost:3000/api/dms/viewDM
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsYW4iLCJpYXQiOjE2MzUwODcyNTgsImV4cCI6MTYzNTA5NDQ1OH0.626bctB1-YE4grAynndhbE9cAZbWT6xIKejIRH4hiDE"
}


